// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Elmodis",
            "email": "mateusz-gluch@elmodis.com"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/": {
            "get": {
                "description": "Retrieves and prints API information. This information contains basic API description.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Retrieves basic API information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/ping": {
            "get": {
                "description": "Retrieves and prints ping message.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Pings API",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/version": {
            "get": {
                "description": "Retrieves and prints API version. This information contains API app version information",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Misc"
                ],
                "summary": "Retrieves API Version",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/{organization}/assets/{assetId}": {
            "get": {
                "description": "Currently available scripts\n- events-summary - Summarizes daily state event occurences\n- online-summary - Summarizes daily datasource activity",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Assets"
                ],
                "summary": "Retrieves script data for asset context",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Unique Script Identifier",
                        "name": "scriptName",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "default": "1708300800:1708387200",
                        "description": "Timestamp range in format {startTs}:{endTs}. Timestamps in seconds, tz=UTC",
                        "name": "ts",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Organization Integer Identifier",
                        "name": "organization",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "default": "367",
                        "description": "Comma separated list of Asset IDs",
                        "name": "assetId",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "example": "motor,motor.Psum",
                        "description": "(available in events-summary) Comma separated list of events",
                        "name": "category",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "additionalProperties": true
                            }
                        }
                    }
                }
            }
        }
    },
    "externalDocs": {
        "description": "OpenAPI",
        "url": "https://swagger.io/resources/open-api/"
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "dev-internal-api.elmodis.com",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Internal Scripts API",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
