basePath: /
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: dev-internal-api.elmodis.com
info:
  contact:
    email: mateusz-gluch@elmodis.com
    name: Elmodis
  title: Internal Scripts API
  version: "1.0"
paths:
  /:
    get:
      consumes:
      - application/json
      description: Retrieves and prints API information. This information contains
        basic API description.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Retrieves basic API information
      tags:
      - Misc
  /ping:
    get:
      consumes:
      - application/json
      description: Retrieves and prints ping message.
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Pings API
      tags:
      - Misc
  /version:
    get:
      consumes:
      - application/json
      description: Retrieves and prints API version. This information contains API
        app version information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: Retrieves API Version
      tags:
      - Misc
swagger: "2.0"
